### ISSUE TITLE
ipad Os 13 not detect as ipad or ios

### ISSUE THREAD

**Issue by yaki4** [dreambo8563/vue-device-detector#30]
Ipad with last os (13) is not detect as ipad or ios by library. 
It seems that the userAgent has changed (see this [link](https://stackoverflow.com/questions/57599945/how-to-detect-ios-13-on-javascript) )

**Comment by dreambo8563** [comment]
@yaki4 I will look into this issue, thanks for your feedback

**Comment by vesper8** [comment]
would be very nice if you could add more tablet detection.. currently it seems you only support ipad? could you possible add a "tablet" key similar to how you do mobile, and group many tablet user agents in there?

many thanks!

**Comment by dreambo8563** [comment]
@vesper8 is there any way to detect all different Android tablet ? pls advise

**Comment by yunlonglee** [comment]
ipad not working

**Comment by yaki4** [comment]
You can use `navigator.maxTouchPoints` to determinate if you are on ipad. 
see https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up

**Comment by dreambo8563** [comment]
> You can use `navigator.maxTouchPoints` to determinate if you are on ipad.
> see https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up

I will add it soon, welcome

**Comment by 21stcn** [comment]
Hi. If this plugin is no longer maintained, could you please mention this on the readme. It's frustrating to build a project with it and then realise it is not maintained and can't even detect ipad/ipados. Obviously there is no obligation for you to maintain, but please could you state this so hours aren't wasted building with it only to realise it is deprecated. Thanks.

**Comment by dreambo8563** [comment]
> Hi. If this plugin is no longer maintained, could you please mention this on the readme. It's frustrating to build a project with it and then realise it is not maintained and can't even detect ipad/ipados. Obviously there is no obligation for you to maintain, but please could you state this so hours aren't wasted building with it only to realise it is deprecated. Thanks.

1.1.6 published, pls have a try. and upgraded the vue cli at the mean time
