### ISSUE TITLE
Please add Wechat Miniapp support

### ISSUE THREAD

**Issue by fengerzh** [dreambo8563/vue-device-detector#37]
Some functions may need to deal with different situations even in Wechat and Wechat Miniapp(微信小程序), there are different UAs for both, please split Wechat-all, Wechat-web and Wechat-miniapp, so programs can handle different logics.

**Comment by dreambo8563** [comment]
will look into this issue later

**Comment by dreambo8563** [comment]
https://github.com/dreambo8563/vue-device-detector/pull/41
