### ISSUE TITLE
Vue 3 compatibility

### ISSUE THREAD

**Issue by narsiliko** [dreambo8563/vue-device-detector#48]
Will be plugin available for Vue3?

**Comment by joshistoast** [comment]
I agree that Vue 3 compatibility is a must for this plugin

**Comment by doutatsu** [comment]
bump

**Comment by dreambo8563** [comment]
will working on vue3, maybe next week.

**Comment by dreambo8563** [comment]
https://github.com/dreambo8563/next-vue-device-detector
