### ISSUE TITLE
vulnerability detected through `commitizen`

### ISSUE THREAD

**Issue by thdepauw** [dreambo8563/vue-device-detector#54]
Our npm audit detected a high vulnerability inside the dependencies of `vue-device-detector` through the `commitizen` package:

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High                               │ Prototype Pollution                                                                                                                                │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package                          │ merge                                                                                                                                                    │
│ Patched in                      │ >=2.1.1                                                                                                                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of              │ vue-device-detector                                                                                                                               │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path                               │ vue-device-detector > commitizen > find-node-modules > merge                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info                      │ https://npmjs.com/advisories/1666                                                                                                       │
└───────────────┴──────────────────────────────────────────────────────────────┘ 
(Sorry for bad layout, it wont stick)

I'm aware this cannot be fixed here, but I did wonder why `commitizen` is set not as `devDependencies`. Looking into the package, it does not seem to contribute in the final released code.

I haven't used `commitizen` myself, but am curious to know if having it as a `dependency` instead of a `devDependency` is required.

**Comment by dreambo8563** [comment]
package.json changed by some plugin I guess. already modified
